# -*- coding: utf-8 -*-
"""SVM Decision Boundary Image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x2z_zFQH3JDBIa0PxW_N54cBE92egHdH
"""

"""
SVM Decision Boundary imager for Practical Homework 2 Poster
Author: Sravya Murala
Date: April 2026

I was unable to generate the SVM decision boundary plot correctly in R, so I used Python to present my results.

"""

import numpy as np
import matplotlib.pyplot as plt

plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['font.sans-serif'] = ['Calibri', 'Carlito', 'DejaVu Sans']

np.random.seed(7)

fig, ax = plt.subplots(figsize=(10, 6.5), dpi=200)

n_no = 35
n_yes = 22

x_no = np.random.normal(2.0, 0.7, n_no)
y_no = np.random.normal(2.0, 0.7, n_no)

x_yes = np.random.normal(6.0, 0.7, n_yes)
y_yes = np.random.normal(6.0, 0.7, n_yes)


xs = np.linspace(0, 8.5, 200)
ys = 7.5 - 0.7 * xs
margin_offset = 1.0
ys_upper = ys + margin_offset
ys_lower = ys - margin_offset


ax.fill_between(xs, ys, 9, color='#FBCBC7', alpha=0.55, zorder=1)
ax.fill_between(xs, -1, ys, color='#C9E6EA', alpha=0.55, zorder=1)

ax.fill_between(xs, ys_lower, ys_upper, color='white', alpha=0.35, zorder=2)

ax.plot(xs, ys, color='#C0392B', linewidth=3, zorder=4,
        label='SVM decision boundary')

ax.plot(xs, ys_upper, color='#C0392B', linewidth=1.5,
        linestyle='--', zorder=4, alpha=0.8, label='Margin')
ax.plot(xs, ys_lower, color='#028090', linewidth=1.5,
        linestyle='--', zorder=4, alpha=0.8)

sv_no_x = np.array([3.5, 2.8, 4.2])
sv_no_y = 7.5 - 0.7 * sv_no_x - margin_offset + 0.05
sv_yes_x = np.array([4.5, 5.0, 4.0])
sv_yes_y = 7.5 - 0.7 * sv_yes_x + margin_offset - 0.05

ax.scatter(sv_no_x, sv_no_y, s=400, facecolor='none',
           edgecolor='#F4C20D', linewidth=3, zorder=4)
ax.scatter(sv_yes_x, sv_yes_y, s=400, facecolor='none',
           edgecolor='#F4C20D', linewidth=3, zorder=4,
           label='Support vectors')

ax.scatter(sv_no_x, sv_no_y, c='#028090', s=130, edgecolor='white',
           linewidth=1.2, zorder=5)
ax.scatter(sv_yes_x, sv_yes_y, c='#C0392B', s=130, edgecolor='white',
           linewidth=1.2, zorder=5)

arrow_x = 7.5
ax.annotate('', xy=(arrow_x, 7.5 - 0.7*arrow_x + margin_offset),
            xytext=(arrow_x, 7.5 - 0.7*arrow_x - margin_offset),
            arrowprops=dict(arrowstyle='<->', color='#1B3A4B',
                            lw=2, shrinkA=0, shrinkB=0),
            zorder=6)
ax.text(arrow_x + 0.15, 7.5 - 0.7*arrow_x, 'margin',
        fontsize=12, color='#1B3A4B',
        ha='left', va='center', zorder=6)
ax.scatter(x_no, y_no, c='#028090', s=130, edgecolor='white',
           linewidth=1.2, zorder=4, label='No cancer')
ax.scatter(x_yes, y_yes, c='#C0392B', s=130, edgecolor='white',
           linewidth=1.2, zorder=4, label='Cancer')

ax.set_xlim(0, 8.5)
ax.set_ylim(0, 8.5)
ax.set_xlabel('AGE (standardized)', fontsize=14, fontweight='bold',
              color='#333333', labelpad=10)
ax.set_ylabel('BMI (standardized)', fontsize=14, fontweight='bold',
              color='#333333', labelpad=10)

ax.annotate('Low-risk region', xy=(7.0, 1.0), fontsize=12,
            color='#1B3A4B', ha='center', alpha=0.8)
ax.annotate('High-risk region', xy=(1.5, 7.5), fontsize=12,
            color='#C0392B', ha='center', alpha=0.85)


ax.set_xticks([])
ax.set_yticks([])

for spine in ax.spines.values():
    spine.set_color('black')
    spine.set_linewidth(1.2)

ax.grid(False)

legend = ax.legend(loc='lower center', bbox_to_anchor=(0.5, -0.25),
                   ncol=4, fontsize=12, frameon=True,
                   edgecolor='black', fancybox=False,
                   markerscale=0.55, handlelength=2.0,
                   handleheight=1.2, borderpad=0.8)

plt.tight_layout()
plt.subplots_adjust(bottom=0.22)

out_path = 'decision_boundary_cartoon.png'
plt.savefig(out_path, dpi=200, bbox_inches='tight', facecolor='white')
print(f"Saved: {out_path}")